from distutils.core import setup
setup(name='utensils',
      version='.01',
      author='Cary Thomson',
      author_email='cary.thomson@gmail.com',
      url='www.example.com',
      packages=[
          'application',
          'classproperty',
          'date',
          'lookup',
          'money',
          'null',
          'plural',
          'point',
          'quantity',
          'registered',
          'sphinxutensils',
          'statemachine',
          'stats',
          'testing',
          'uri',
      ],
      )